/* config.h.  Generated by configure.  */
/* config.hin.  Generated from configure.in by autoheader.  */

/* EINTR errno value */
#define EINTR 4

/* Define if acosh() is available. */
#define HAVE_ACOSH 1

/* Define if asinh() is available. */
#define HAVE_ASINH 1

/* Define if atanh() is available. */
#define HAVE_ATANH 1

/* Define if cbrt() is available. */
#define HAVE_CBRT 1

/* Define if ceil() is available. */
#define HAVE_CEIL 1

/* Define if copysign() is available. */
#define HAVE_COPYSIGN 1

/* Define to 1 if you have the <ctype.h> header file. */
#define HAVE_CTYPE_H 1

/* Define if erf() is available. */
#define HAVE_ERF 1

/* Define if erfc() is available. */
#define HAVE_ERFC 1

/* Define to 1 if you have the <errno.h> header file. */
#define HAVE_ERRNO_H 1

/* Define if expm1() is available. */
#define HAVE_EXPM1 1

/* Define to 1 if you have the <float.h> header file. */
#define HAVE_FLOAT_H 1

/* Define if floor() is available. */
#define HAVE_FLOOR 1

/* Define if fmod() is available. */
#define HAVE_FMOD 1

/* Define if hoc is to be compiled with double precision */
#define HAVE_FP_T_DOUBLE 1

/* Define if hoc is to be compiled with quadruple precision */
/* #undef HAVE_FP_T_QUADRUPLE */

/* Define if hoc is to be compiled with single precision */
/* #undef HAVE_FP_T_SINGLE */

/* Define if gamma() is available. */
#define HAVE_GAMMA 1

/* Define if getgid() is available. */
#define HAVE_GETGID 1

/* Define if getpid() is available. */
#define HAVE_GETPID 1

/* Define if getppid() is available. */
#define HAVE_GETPPID 1

/* Define if getuid() is available. */
#define HAVE_GETUID 1

/* Define if GNU readline support is available */
#define HAVE_GNU_READLINE 1

/* Define if hypot() is available. */
#define HAVE_HYPOT 1

/* Define if host arithmetic is IEEE 754 */
#define HAVE_IEEE_754 1

/* Define if ilogb() is available. */
#define HAVE_ILOGB 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define if j0() is available. */
#define HAVE_J0 1

/* Define if j1() is available. */
#define HAVE_J1 1

/* Define if jn() is available. */
#define HAVE_JN 1

/* Define if ldexp() is available. */
#define HAVE_LDEXP 1

/* Define if lgamma() is available. */
#define HAVE_LGAMMA 1

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you have the <locale.h> header file. */
#define HAVE_LOCALE_H 1

/* Define if log1p() is available. */
#define HAVE_LOG1P 1

/* Define to 1 if the system has the type `long double'. */
#define HAVE_LONG_DOUBLE 1

/* Define to 1 if the system has the type `long long'. */
#define HAVE_LONG_LONG 1

/* Define if printf for long long requires %L[diouxX]. */
/* #undef HAVE_LONG_LONG_FORMAT_L */

/* Define if printf for long long requires %ll[diouxX]. */
#define HAVE_LONG_LONG_FORMAT_LL 1

/* Define to 1 if you have the <malloc.h> header file. */
#define HAVE_MALLOC_H 1

/* Define to 1 if you have the <math.h> header file. */
#define HAVE_MATH_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define if nearest() is available. */
/* #undef HAVE_NEAREST */

/* Define if nextafter() is available. */
#define HAVE_NEXTAFTER 1

/* Define to 1 if you have the <readline/history.h> header file. */
#define HAVE_READLINE_HISTORY_H 1

/* Define to 1 if you have the <readline/readline.h> header file. */
#define HAVE_READLINE_READLINE_H 1

/* Define if remainder() is available. */
#define HAVE_REMAINDER 1

/* Define if rint() is available. */
#define HAVE_RINT 1

/* Define if rsqrt() is available. */
/* #undef HAVE_RSQRT */

/* Define if scalb() is available. */
#define HAVE_SCALB 1

/* Define to 1 if you have the <setjmp.h> header file. */
#define HAVE_SETJMP_H 1

/* Define to 1 if you have the <signal.h> header file. */
#define HAVE_SIGNAL_H 1

/* Define if significand() is available. */
#define HAVE_SIGNIFICAND 1

/* Define to 1 if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* Define if snprintf() has a prototype in stdio.h. */
#define HAVE_SNPRINTF_PROTOTYPE 1

/* Define to 1 if you have the <stddef.h> header file. */
#define HAVE_STDDEF_H 1

/* Define to 1 if you have the <stdint.h> header file. */
/* #undef HAVE_STDINT_H */

/* Define to 1 if you have the <stdio.h> header file. */
#define HAVE_STDIO_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strftime' function. */
#define HAVE_STRFTIME 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define if strtold() is available. */
/* #undef HAVE_STRTOLD */

/* Define to 1 if you have the <sunmath.h> header file. */
#define HAVE_SUNMATH_H 1

/* Define to 1 if you have the <sys/resource.h> header file. */
#define HAVE_SYS_RESOURCE_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <time.h> header file. */
#define HAVE_TIME_H 1

/* Define if trunc() is available. */
/* #undef HAVE_TRUNC */

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define if host file system is UNIX(-like) */
#define HAVE_UNIX_HOME_DIRECTORY 1

/* Define to 1 if you have the <values.h> header file. */
#define HAVE_VALUES_H 1

/* Define if y0() is available. */
#define HAVE_Y0 1

/* Define if y1() is available. */
#define HAVE_Y1 1

/* Define if yn() is available. */
#define HAVE_YN 1

/* Package bug-reporting address */
#define PACKAGE_BUGREPORT "Nelson H. F. Beebe <beebe@math.utah.edu>"

/* Package date */
#define PACKAGE_DATE "09-Aug-2002"

/* Package name */
#define PACKAGE_NAME "hoc"

/* Package string */
#define PACKAGE_STRING "hoc 7.0.6.beta"

/* Package tarname */
#define PACKAGE_TARNAME "hoc"

/* Package version */
#define PACKAGE_VERSION "7.0.6.beta"

/* SIGXCPU signal value */
#define SIGXCPU 30

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define if needed to expose erf(), erfc() in <math.h> */
/* #undef _ALL_SOURCE */

/* Define if needed to expose erf(), erfc() in <math.h> */
/* #undef _XOPEN_SOURCE */

/* Define if needed to expose struct timeval in <time.h> */
/* #undef _XPG4_2 */

/* Define if needed to expose significand() in <math.h> */
/* #undef __EXTENSIONS__ */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */


#include "stdc.h"

